### ISSUE TITLE
Đổi trong phần quản lý admin từ xóa thành ẩn 

### ISSUE THREAD

**Issue by CaoThanhNammm** [21130449-NguyenKhaiNam/web-sell#10]
chỉ có thể ẩn chứ không thể xóa trong DB vì ảnh hưởng các liên kết với các bảng khác
- chức năng xóa đơn hàng thì không cần thiết => bỏ 
- chức năng xóa khách hàng sẽ thành ẩn khách hàng
note: trường isVerify sẽ thêm số 2 nghĩa là khách hàng bị ẩn

**Comment by 21130449-NguyenKhaiNam** [comment]
Chức năng xóa đơn hàng có cần thiết vì:
- Người dùng hủy đơn -> Trạng thái lúc đó chưa giao
- Người bán hủy đơn do trục trặc -> Trang thái lúc đó đang chuẩn bị
Tuy nhiên theo cá nhân tui nghĩ nên chuyển từ xóa thành ẩn vì có thể giải quyết nhiều tình huống khác nhau.

**Comment by 21130449-NguyenKhaiNam** [comment]
Vậy nếu có trường hợp: 
- Giao hàng người dùng không nhận và đơn được hoàn lại
- Người dùng sử dụng thanh toán thẻ ngân hàng và khi giao hàng không nhận liên lạc cũng không thành công

**Comment by CaoThanhNammm** [comment]
thì đơn vẫn là hủy, chứ s lại xóa hay ẩn đi được

**Comment by CaoThanhNammm** [comment]
giao không thành công mà đã thanh toán rồi thì phải hoàn trả lại số tiền => thống kê vẫn đúng

**Comment by 21130449-NguyenKhaiNam** [comment]
Thì ý tui là thành công mới cộng tuy nhiên trong trường hợp đã nếu trước đó đơn hàng giao khách thanh toán rồi, nhưng liên hệ hoàn lại số tiền không được thì 70k này đang bị chơi vơi nếu không có biện pháp xử lý thì sẽ bị lỗ hỏng ở database
- Đã đưa ra giải pháp thêm "Ẩn" -> những đơn hàng không xác định
