### ISSUE TITLE
Lỗi khởi động đồ án

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#11]
- Liệt kê các lỗi và cách xử lý tương ứng

**Comment by 21130449-NguyenKhaiNam** [comment]
- Lỗi không tìm thấy class Bean
![Screenshot 2024-03-07 080117](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/e20cb79d-e3bb-4207-9947-88b5c816a804)

**Comment by 21130449-NguyenKhaiNam** [comment]
Sử dụng IDE khác

**Comment by ducvui2003** [comment]
> Sử dụng IDE khác

(Khuyến nghị sử dụng intellij IDEA)

**Comment by 21130449-NguyenKhaiNam** [comment]
> Lỗi khởi động ở intelliJ ![image](https://private-user-images.githubusercontent.com/144084815/311174760-eec8783a-9da0-4f5f-81b6-8e17f0c0f080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODgxOTYsIm5iZiI6MTcwOTg4Nzg5NiwicGF0aCI6Ii8xNDQwODQ4MTUvMzExMTc0NzYwLWVlYzg3ODNhLTlkYTAtNGY1Zi04MWI2LThlMTdmMGMwZjA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwODUxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjMyYmMyNTJmNDA3ZTM1ZjdjZGNlN2NmNWQ0N2UyMDg1MTkyNjM5MjRhMmQ5ZDk2OWM1NDI3NDIxNDZiNDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RpRwq_HtOq8N077sbpq25s0jEGGm5MNnpbWZ7hUMBwE)

Kiểm tra nội dung của file db và check các đường dẫn tại các file .properties

**Comment by 21130449-NguyenKhaiNam** [comment]
Lỗi "MySQL Shutdown Unexpectedly Error" từ XAMPP.
[Link fix lỗi](https://stackoverflow.com/questions/4758844/error-1067-the-process-terminated-unexpectedly-when-trying-to-start-mysql)

**Comment by 21130449-NguyenKhaiNam** [comment]
![Screenshot 2024-03-24 151225](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/2fcd8970-3224-4ae5-96e6-9d29638629df)
Các hướng xử lý:
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/4493513c-77a6-4351-b75f-e4880c83f755)
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/e96a1cbe-4729-44d8-af0f-6850effe8707)
