### ISSUE TITLE
Lỗi đường dẫn không hoạt động

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#12]
Thử đổi sang core tag
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/e6f734c8-f2a2-4d26-ba9a-30d44cc34913)

**Comment by 21130449-NguyenKhaiNam** [comment]
Đường dẫn khi sử dụng không hợp lệ, ví dụ:
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/bc86e7b5-a2d7-48a2-80b8-2c0a88babba4)

*** Hãy thử đổi thành:  ***
![Screenshot 2024-03-09 181629](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/ea3b2660-7368-4ca9-9d49-d91c467732c4)

*** Hoặc thêm initParam phía trước rồi .cont... như ảnh 2 ***

**Comment by 21130449-NguyenKhaiNam** [comment]
Lỗi các đường dẫn ảnh:
Thử check lại trong tomcat loại bỏ đi tiền tố /tên_đồ_án hoặc xem xét lại vị trí trỏ tới của đường dẫn

**Comment by 21130449-NguyenKhaiNam** [comment]
Đối với các form:
- Thử so sánh tên với các thư mục filter hoặc web
- Thêm / trước tên các form lọc

**Comment by ducvui2003** [comment]
Hướng sửa lỗi: 
1 Đối với attr **action** trong <form> 
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/83511167/12f70858-4d63-4d76-9cd6-32e59b06aa43)
Đổi từ: 
`<form action="filterProductBuying" class="form__filter">`
Sang: 
`<form action="/filterProductBuying" class="form__filter">`
2. Đối với ajax trong js
- url bắt đầu  = "/"
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/83511167/f3f5e845-7c85-403b-b9c8-5d37b468c81e)
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/83511167/8411b22b-03d2-4431-9849-8f490ccef07f)
