### ISSUE TITLE
nâng cấp paging

### ISSUE THREAD

**Issue by CaoThanhNammm** [21130449-NguyenKhaiNam/web-sell#14]
chỉ hiện mỗi lần 5 trang
khi trang đầu tiên bị mất sẽ hiện ra trang số 1

**Comment by CaoThanhNammm** [comment]
những trang sẽ hiện được tính như sau: trang hiện tại +- 2, nếu trang hiện tại lớn hơn 3 thì trang 1 không bị mất hoặc có thể hiểu là trang 1 sẽ luôn tồn tại

**Comment by 21130449-NguyenKhaiNam** [comment]
Vậy nếu người dùng đang ở trang 8 và muốn quay về trang 2 thì như thế nào?

**Comment by 21130449-NguyenKhaiNam** [comment]
https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/f18229a7-b0c7-4429-8521-81cd725982a3

Gợi ý 1 cách xử lý

**Comment by 21130449-NguyenKhaiNam** [comment]
Gợi ý thư viện: [Tippy lib](https://atomiks.github.io/tippyjs/)

**Comment by CaoThanhNammm** [comment]
trang 8 sẽ hiện các trang 1 6 7 8 9 10, muốn về trang 2 thì ấn về 1 rồi sang 2

**Comment by 21130449-NguyenKhaiNam** [comment]
[Mẫu code xử lý](https://codesandbox.io/p/sandbox/nav-pages-when-so-many-tsldkz)

**Comment by CaoThanhNammm** [comment]
đã làm xong
