### ISSUE TITLE
xử lý phân trang trong admin

### ISSUE THREAD

**Issue by CaoThanhNammm** [21130449-NguyenKhaiNam/web-sell#15]
tạo ra 1 trang jsp chứa các thứ tự trang vì có nhiều trang sử dụng chung
trang nào xử lý phân trang rồi thì không làm

**Comment by 21130449-NguyenKhaiNam** [comment]
Ông có thể giải thích chi tiết hoặc thêm hình ảnh không vì tui chưa hiểu ý của ông lắm

**Comment by CaoThanhNammm** [comment]
thì trang nào có phân trang chỉ cần dùng include, và tạo filter gửi các attribute cần thiết đi là được
