### ISSUE TITLE
Lưu trữ ảnh

### ISSUE THREAD

**Issue by ducvui2003** [21130449-NguyenKhaiNam/web-sell#18]
# Lưu trữ trên cục bộ
- Ưu điểm:
  - Tốc độ truy xuất + lưu trữ nhanh
  - Dễ quản lý
  - Không giới hạn về gb lưu trữ
- Nhược điểm: 
  - Khó đồng bộ khi test local
# Lưu trữ thông qua cloud
## cloudinary
- Ưu điểm:
   -  Tốc độ truy xuất + lưu tùy thuộc vào mạng
   -  Build được thông qua maven
   -  Có thể tương tác với tên folder + name image
- Nhược điểm:
  - Tổng dung lương lưu trữ tối đa 25gb 
## firebase
- Ưu điểm:
   -  Tốc độ truy xuất + lưu tùy thuộc vào mạng
   -  Có thể tương tác với tên folder
- Nhược điểm:
   - Tổng dung lượng lưu 5gb
   - Mỗi ngày chỉ request được tối đa 1gb
## google drive
  - Ưu điểm:
     -  Tốc độ truy xuất + lưu tùy thuộc vào mạng
     -  Có thể tương tác với tên folder
  - Nhược điểm:
     - Chỉ build được thông qua gradle

**Comment by 21130449-NguyenKhaiNam** [comment]
Mình cũng cần chú ý xem các lưu trữ trên có cho phép tương tác với thư mục hoặc ảnh bằng code không
