### ISSUE TITLE
Các vấn đề liên quan đến quản lý user của admin

### ISSUE THREAD

**Issue by ducvui2003** [21130449-NguyenKhaiNam/web-sell#19]
# Thêm người dùng
- Loại bỏ từ phía admin
# Nâng quyền, hạ quyền
- Có 4 quyền
 - Locked: khóa tài khoản (-1) -> Thay thế cho việc ẩn
 - User: khách (0)
 - Mod: được xem chi tiết, ko được sử dụng các chức năng làm thay đổi dữ liệu (1)
 - Admin: toàn quyền (2)
 # Nâng cấp form xem chi tiết người dùng
- Sử dụng boostrap form
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/83511167/bf94c60c-d9db-4a58-9654-c0da8f501783)

**Comment by CaoThanhNammm** [comment]
- quyền locked là quyền gì. Nói về role thì có user, mod và admin. còn locked chỉ ở bảng user không được liệt kê vào quyền
- mà cho tui hỏi ông xử lý xóa khách hàng bên admin luôn hả

**Comment by 21130449-NguyenKhaiNam** [comment]
- Locked có thể xem như khách hàng không trung thực - tức tài khoản này không thể truy cập hệ thống (Có thể tên chưa hợp lý lắm)
- Cái xử lý mấy vụ xóa thành ẩn hiện gì đó thì tui quy lại thành 1 việc là tối ưu db nha ông

> * quyền locked là quyền gì. Nói về role thì có user, mod và admin. còn locked chỉ ở bảng user không được liệt kê vào quyền
> * mà cho tui hỏi ông xử lý xóa khách hàng bên admin luôn hả

**Comment by ducvui2003** [comment]
> * quyền locked là quyền gì. Nói về role thì có user, mod và admin. còn locked chỉ ở bảng user không được liệt kê vào quyền
> * mà cho tui hỏi ông xử lý xóa khách hàng bên admin luôn hả

Bây h có 2 hướng để xử lý vụ ẩn. 
- Thêm 1 cột ẩn/hiện cho bảng user
- Tạo 1 role thấp hơn user để ẩn user

**Comment by CaoThanhNammm** [comment]
> > * quyền locked là quyền gì. Nói về role thì có user, mod và admin. còn locked chỉ ở bảng user không được liệt kê vào quyền
> > * mà cho tui hỏi ông xử lý xóa khách hàng bên admin luôn hả
> 
> Bây h có 2 hướng để xử lý vụ ẩn.
> 
> * Thêm 1 cột ẩn/hiện cho bảng user
> * Tạo 1 role thấp hơn user để ẩn user
>   Còn tui muốn hỏi là có nên cho admin chủ động tạo user không á (user khi tạo sẽ mặc định là đã xác thực)

- nên thay datatype của isVerify thành int: 0 là chưa xác thực(mặc định nghĩa là khi vừa tạo acc sẽ là cái này), 1 là đã xác thực, 2 là khóa,...
- có. Nếu admin tạo user thì chỉ là mod hoặc là admin luôn(không được quyền tạo user).
-
