### ISSUE TITLE
Lọc không cần reload lại trang

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#21]
- Xử lý việc lọc không cần reload lại trang cho mọi nơi có liên quan đến lọc sản phẩm của hệ thống: admin và user
- Chức năng lọc gọi thông qua ajax và cần đảm bảo có api gọi riêng để có thể tái sử dụng

**Comment by ducvui2003** [comment]
Này là hướng nghĩ của tui, chưa thử nghiệm, có đánh số thứ tự workflow
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/83511167/937aa410-499e-4ac7-abc7-e88549dc9451)

**Comment by 21130449-NguyenKhaiNam** [comment]
> Này là hướng nghĩ của tui, chưa thử nghiệm, có đánh số thứ tự workflow ![image](https://private-user-images.githubusercontent.com/83511167/315189887-937aa410-499e-4ac7-abc7-e88549dc9451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTcxNzcsIm5iZiI6MTcxMTAxNjg3NywicGF0aCI6Ii84MzUxMTE2Ny8zMTUxODk4ODctOTM3YWE0MTAtNDk5ZS00YWM3LWFiYzctZTg4NTQ5ZGM5NDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEwMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYjJjMjMzOGMwODIwMWJlZGRiNGExNzEzOTIzMjVmZTVkZWJhMTY1MjYxZjIzNjg0MTk1NTZhZjYyMDE2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.72LuDOWkNBZwIlh0aEocOvkRLYbYJxhNfMBZZ9ll6PE)

Ok ông tui cũng làm theo hướng này, tuy nhiên gặp vấn đề ở chỗ xử lý tải sản phẩm lên nếu ông có ý tưởng nào thì hỗ trợ tui với nha, thanks ông: 
https://github.com/21130449-NguyenKhaiNam/web-sell/issues/24#issue-2199781032

**Comment by 21130449-NguyenKhaiNam** [comment]
#1: 
- Hoàn tất lọc ở phía user tuy nhiên code có vẻ chưa được tối ưu, sau khi hoàn thành toàn bộ phần lọc cần tối ưu lại

**Comment by 21130449-NguyenKhaiNam** [comment]
#2:
- Hoàn tất lọc không reload lại trang ở admin
- Nhận thấy cần tối ưu và việc lặp code ở phía server khá nhiều
- Cần tối ưu code tại js ajax
