### ISSUE TITLE
Cách tải sản phẩm lên khi đã gọi được API

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#24]
- Tui gặp khó khăn trong việc tải sản phẩm lên ghi gọi API, mọi người ai có hướng xử lý nào không

https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/218a5dc6-5ae3-4eb8-bc74-0e12030bf580

**Comment by ducvui2003** [comment]
- khi ajax trả về data thì ông truy cập vào data.products (array)
- Tạo 1 mảng `result` chứa kết quả
- Sử dụng map hoặc vòng lặp qua array, ở mỗi phần từ thì ông sẽ trả về string (chứa các mã HTML cấu hình nên card) kèm theo là dữ liệu lấy được từ phần từ đó (name, category, link ảnh, ...) (sử dụng Template strings của js để gán biến).
- Kết quả trả về mỗi phần từ thì ông đẩy vào `result`
- Khi này `result` ông đang chứa 1 array các string HTML
- Select `element` chưa danh sách sản phẩm -> xóa HTML bên trong bằng `element.innerHTML = ""`;
- Đưa `result ` vào `element` bằng `element.innerHTML = result.join("")` (`join("")` nối mọi phần từ trong mảng lại thành 1 string)

**Comment by ducvui2003** [comment]
Ví dụ như:
```
const listProductElement = document.querySelector(".product__list");
function loadProducts(arrayProducts) {
    const vndFormat = Intl.NumberFormat("vi-VI", {
        style: "currency",
        currency: "VND",
    });
    listProductElement.innerHTML = "";
    let html = arrayProducts.map(function (product) {
        return ` <div class = "product__item" >
                    <img src = "assets/img/product_img/${product.nameImage}" class="product__img" >
                    <div class = "product__info" >
                        <a class="product__name" target="_blank" href="../htmls/productDetail.jsp">${product.name}</a>
                        <div class="product__review">
                            <div class="product__review-stars">
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                            </div>
                            <a class="product__review-num" target="_blank" href="../htmls/productDetail.jsp">${product.reviews} nhận xét</a>
                        </div>
                        <span class="product__price"><strong class="product__price--sale">${vndFormat.format(product.salePrice)}</strong> <strong class="product__price--original">${vndFormat.format(product.originalPrice)}</strong></span>
                    </div>
                </div>`;
    });
    listProductElement.innerHTML = html.join("");
    console.log("Load success")
}
```

**Comment by 21130449-NguyenKhaiNam** [comment]
Oki thanks ông dựa trên ý tưởng đề cập tui đã tìm được hướng giải quyết phù hợp
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/92699fc6-ef18-417d-ad46-a9ecb4682825)
