### ISSUE TITLE
lỗi khi kiểm tra chức năng "tìm kiếm" trong branch fixMerge

### ISSUE THREAD

**Issue by CaoThanhNammm** [21130449-NguyenKhaiNam/web-sell#36]
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144134943/c027a643-c3b8-438f-9bb6-f24836ba9ab4)
- khi tìm kiếm tầm cứ mỗi khoảng 5s sau nó sẽ hiện ra lỗi này
- tìm kiếm chậm

**Comment by 21130449-NguyenKhaiNam** [comment]
À ok ông tui đã xác định được vấn đề sinh ra lỗi. Về vấn đề tải chậm thì là do câu query trong db bị lỗi (nếu ông để ý nhập gì nó cũng lấy tất cả)
