### ISSUE TITLE
Cải thiện trang thông tin khách hàng để phục vụ phần thanh toán

### ISSUE THREAD

**Issue by ducvui2003** [21130449-NguyenKhaiNam/web-sell#38]
- Tiến hành tách cột address trong user thành 4 cột nhỏ:
   address -> province (tỉnh + thành phố) + district (huyện/ quận) + ward (xã/phường) + số nhà/tên đường.
- Phương án: 
  Sử dụng API GHN để lấy ra thông tin địa chỉ + kết hợp việc tính phí sau này

**Comment by ducvui2003** [comment]
@21130449-NguyenKhaiNam ý kiến tui vậy, nếu thấy ổn thì xác nhận để tui làm nh ông.

**Comment by 21130449-NguyenKhaiNam** [comment]
Okay ông, hôm trước Đức có trình bày tui cũng có tham khảo thì thấy cách đó okay đó ông, ông triển khai nha

**Comment by ducvui2003** [comment]
Sử dụng api [map4d](https://docs.map4d.vn/map4d-service/api/v1.2/#/api_geocode_v2) để kiểm tra tính hợp lệ của địa chỉ (không sử dụng googel api được vì Việt Nam bị chặn dịch vụ)

**Comment by ducvui2003** [comment]
Hiện tại đã cải thiện xong phần xem đơn hàng dành cho user. Xử lý phần voucher xong sẽ quay lại tích hợp tiếp.
