### ISSUE TITLE
Thêm lại các chức năng bị ảnh hưởng khi thực hiện merge

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#55]
- Thêm lại các chức năng bị ảnh hưởng bởi việc hợp nhất ứng dụng
- Tối ưu giao diện nếu có
- Áp dụng UI/UX cho ứng dụng (nếu có)

**Comment by 21130449-NguyenKhaiNam** [comment]
- Trong lần merge gần nhất đã quên điều này nên sẽ thực hiện kiểm tra và bổ sung sau

**Comment by ducvui2003** [comment]
newsProduct.jsp: Lỗi chuyển trang
trendingProduct.jsp: lỗi chuyển trang
adminOrder.jsp: Lỗi chuyển trang
adminUser.jsp: Lỗi chuyển trang
productDetail.jsp: 
- Chưa đưa các lựa chọn vào select2 để thu gọn 
- Ngừoi dùng không cần chọn màu vẫn có thể thêm sản phẩm vào giỏ hàng (màu của sản phẩm đó sẽ là màu đầu tiên
- Lỗi khi chuyển tới trang đặt mua sản phẩm theo yêu cầu

**Comment by 21130449-NguyenKhaiNam** [comment]
- Chức năng không thể xóa sản phẩm trong giỏ hàng: Do sai đường dẫn
- Không hiển thị ảnh: Do sự thay đổi cách sử dụng đường dẫn ảnh
- Lọc có hoạt động: Tuy nhiên nếu không tìm thấy nó sẽ hiển thị những sản phẩm phổ biến (Chỉ mới kiểm tra và sửa chữa một số lỗi nhỏ ở user)

**Comment by 21130449-NguyenKhaiNam** [comment]
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/c0e9f91e-d4d8-41d6-b61d-66cfdea35ce8)
Lỗi phân tích chuỗi trong log: Đang kiểm tra và điều chỉnh
