### ISSUE TITLE
Sửa lỗi thanh toán giỏ hàng 

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#62]

**Comment by 21130449-NguyenKhaiNam** [comment]
Lỗi hiển thị vì không xác định được dữ liệu dưới server:
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/1e5ef1db-65af-4a81-8e61-16f215abab44)
Dự kiến fix:
+ Màu sắc: Sử dụng thư viện color-name-list
+ Kích thước chỉ để lại thông tin nameSize

**Comment by 21130449-NguyenKhaiNam** [comment]
Lỗi bất đồng giỏ hàng khi chuyển đổi sang một trang khác: 
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/72ad7a4e-b37a-4f67-a717-27fbba3dd77f)

**Comment by 21130449-NguyenKhaiNam** [comment]
Thiếu ảnh thanh toán online 
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/16734dd7-707a-4111-920b-76102ecb6390)

**Comment by 21130449-NguyenKhaiNam** [comment]
Lỗi bất đồng khi sản phẩm có nhiều model, do bắt sự kiện thay đổi chỉ có thể xem xét số lượng mà chưa xem xét ở bên trong
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/1cfa826b-f6c9-4dc2-b288-0665cbc66cfc)

**Comment by ducvui2003** [comment]
> Thiếu ảnh thanh toán online ![image](https://private-user-images.githubusercontent.com/144084815/335791939-16734dd7-707a-4111-920b-76102ecb6390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTU2MjUsIm5iZiI6MTcxNzI5NTMyNSwicGF0aCI6Ii8xNDQwODQ4MTUvMzM1NzkxOTM5LTE2NzM0ZGQ3LTcwN2EtNDExMS05MjBiLTc2MTAyZWNiNjM5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMjI4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODUxMGYxODA2OTFmMGEzYWQzMDg4NTM2ZmRhOGIxZjYyMDU3MDMzNzIzMzZkZDg1MzYwNjczOWIzN2U2ODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k3bs1ypm5EaR9O7QyWlZnvTij0UaU92wyeXnLC1bbFg)

Có gi ông kiếm ảnh khác thay thế nha Nam

**Comment by 21130449-NguyenKhaiNam** [comment]
> Lỗi bất đồng khi sản phẩm có nhiều model, do bắt sự kiện thay đổi chỉ có thể xem xét số lượng mà chưa xem xét ở bên trong ![image](https://private-user-images.githubusercontent.com/144084815/335837397-1cfa826b-f6c9-4dc2-b288-0665cbc66cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTMwNzIsIm5iZiI6MTcxNzM5Mjc3MiwicGF0aCI6Ii8xNDQwODQ4MTUvMzM1ODM3Mzk3LTFjZmE4MjZiLWY2YzktNGRjMi1iMjg4LTA2NjVjYmM2NmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwNTMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjY4M2JiMGI1M2RmNzJmYTUwNjQ4NzBkNGNiODcwOTlmYTFjNzE5NTY3NjAyOTU2MDRmMzI0ZTVhODcyM2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xN3xF7JRxnDireMki1EDkxuMam3TnaKywmlOQmcArno)

Đã xử lý bằng cách thay đổi tham chiếu -> tham trị và sử dụng 1 kỹ thuật trong cắt list, kết hợp  thư viện  thư viện Guava của Google có sẵn trong java 
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/b4b3026c-4f6f-4e82-a20b-1905cff0b76d)

**Comment by 21130449-NguyenKhaiNam** [comment]
> Lỗi hiển thị vì không xác định được dữ liệu dưới server: ![image](https://private-user-images.githubusercontent.com/144084815/334311957-1e5ef1db-65af-4a81-8e61-16f215abab44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTAzMjEsIm5iZiI6MTcxNzU1MDAyMSwicGF0aCI6Ii8xNDQwODQ4MTUvMzM0MzExOTU3LTFlNWVmMWRiLTY1YWYtNGE4MS04ZTYxLTE2ZjIxNWFiYWI0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMTEzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjE0MDkyMjFkZTU1MDg5NWMzZTU0OTMxZWE4MmYyMDQ1YWU4MjYzYjFjMTY3MmY4OWEzNzA3YWIxZDBkZWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o3zzQL9XzJd6HqYEEaE5KUQ_roTfCxpU6MeWUn-996I) Dự kiến fix:
> 
> * Màu sắc: Sử dụng thư viện color-name-list || Nếu chỉ có màu cố định thì làm mảng convert qua lại
> * Kích thước chỉ để lại thông tin nameSize

Sử dụng hàm có sẵn trong lớp CartProductCustom để chuyển json size về dạng cấu trúc được quy định

**Comment by 21130449-NguyenKhaiNam** [comment]
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/ec41a34d-082e-4524-bdf3-3383775ad90e)
Lỗi do lưu trữ sai định dạng json khi thêm vào giỏ hàng

**Comment by 21130449-NguyenKhaiNam** [comment]
# Lỗi có cập nhật từ session -> db nhưng chưa cập nhật từ db -> session 
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/5859f5fb-4cab-4a5f-ad24-280d9782cb80)

**Comment by 21130449-NguyenKhaiNam** [comment]
> ![image](https://private-user-images.githubusercontent.com/144084815/336654925-ec41a34d-082e-4524-bdf3-3383775ad90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTE0MTQsIm5iZiI6MTcxNzU1MTExNCwicGF0aCI6Ii8xNDQwODQ4MTUvMzM2NjU0OTI1LWVjNDFhMzRkLTA4MmUtNDUyNC1iZGYzLTMzODM3NzVhZDkwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMTMxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWRiMmExYjNkYjdmZGU5MmI5MjIwNTUxYmFhY2Q5ODI5NmFjMmI3ZGI1NmQ5ZWQ2NTljZjBiMjVhMGZhMDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1s46uTUpc32krnmV8Nwc1R43bWKylJPAjuyyWrw67N8) Lỗi do lưu trữ sai định dạng json khi thêm vào giỏ hàng

Đã sửa bằng cách thay định dạng toString:
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/3acb7b17-7991-4c62-b500-7f8d06c18654)
