### ISSUE TITLE
Sửa chữa các lỗi khác của dự án 

### ISSUE THREAD

**Issue by 21130449-NguyenKhaiNam** [21130449-NguyenKhaiNam/web-sell#64]

**Comment by 21130449-NguyenKhaiNam** [comment]
# Lỗi đôi lúc không nhận định được loại query trong log 
![image](https://github.com/21130449-NguyenKhaiNam/web-sell/assets/144084815/fbcc8fc6-8cea-4279-acf2-6c582422e416)

**Comment by ducvui2003** [comment]
Các lỗi phần update gần nhất (9/6/2024)
- Vấn đề ở voucher khi apply không hiện thông báo
- Lỗi chuyển trang từ adminNavigator sang adminVoucher: 
  - Phần cấu hình method cho jquery validator và và select2 không nhận khi load vào trang adminNavigator
  - Cách giải quyết: chưa có.
- Modal bootstrap bị ghi đè backdrop khi chuyển sang nhiều trang liên tục
  - Modal bootstrap dựa vào thẻ body để tiến hành setup, 1 trang có nhiều thẻ body sẽ bị vấn đề xung đột
  - Cách giải quyết: sử dụng 1 bên thư viện modal khác vd: [jQuery Modal](https://www.jquerymodal.com/)
