### ISSUE TITLE
Sửa lỗi các trang

### ISSUE THREAD

**Issue by CaoThanhNammm** [21130449-NguyenKhaiNam/web-sell#83]
Trang chính
Trang gian hàng
Trang liên hệ
Trang giới thiệu
Trang chi tiết sản phẩm
Trang giỏ hàng
Trang thanh toán
Trang đặt theo yêu cầu

**Comment by 21130449-NguyenKhaiNam** [comment]
Tui thấy có label HELP không biết ông cần hỗ trợ gì vậy nam

**Comment by CaoThanhNammm** [comment]
accountInfo.js trong compile chậm, không thể debug được

**Comment by 21130449-NguyenKhaiNam** [comment]
Tui vừa check lại các trang nam thực hiện thì thấy là có 1 trang nam cần sd tới acccountInfo.js là trang thanh toán để lấy việc thêm địa chỉ mới. 
Tui gợi ý vài các sửa sau, ông thấy cách nào ổn thì phản hồi lại cho tui nha:

- [ ] Tụi mình meet cùng nhau fix chỗ đó
- [ ] Trang đó nam để qua cho tui 
- [ ] Nam thử thay đổi vị trí ưu tiên cho file js đó
- [ ] Check có thể lỗi do nó không giống như cú pháp accountInfo.js mong đợi

**Comment by CaoThanhNammm** [comment]
meet đi Nam
